version: '2.1'
services:
  crawler:
    build: .
    restart: on-failure
    networks:
      - elasticsearch
    volumes:
      - ./out:/app/out
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=changeme
      - CRAWLER_FEEDS_FILE=/app/data/feeds_de.txt
      - CRAWLER_LANGUAGE=german
      - CRAWLER_TIMEZONE=Europe/Berlin

  elasticsearch:
    image: elasticsearch:5.5.2-alpine
    networks:
      - elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:5.5.2
    networks:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  nodcore:
    image: thesoenke/nodcore
    volumes:
      - ./out/nod/german:/app/content

  nodweb:
    image: thesoenke/nodweb
    restart: always
    ports:
      - 9000:9000

  db:
    image: mariadb
    volumes:
      - "nod_data:/var/lib/mysql"
    environment:
       MYSQL_ROOT_PASSWORD: nod
       MYSQL_DATABASE: nodcore
       MYSQL_USER: nod
       MYSQL_PASSWORD: nod
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306


volumes:
  elasticsearch:
  nod_data:

networks:
  elasticsearch: