version: '2.1'
services:
  crawler:
    build: .
    restart: on-failure
    networks:
      - elasticsearch
    volumes:
      - ./out:/app/out
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=changeme
      - CRAWLER_LANGUAGE=german
      - CRAWLER_TIMEZONE=Europe/Berlin

  elasticsearch:
    image: elasticsearch:5.5.2-alpine
    networks:
      - elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - http.cors.enabled=true

  kibana:
    image: kibana:5.5.2
    networks:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  elasticsearch:

networks:
  elasticsearch: